export const TRANSLATE_DICT: Record<string, Record<string, string>> = {
  en: {
    title: "KisanVriddhi",
    tagline: "Empowering Farmers Through Intelligence",
    dashboard: "Dashboard",
    farmProfile: "Farm Profile",
    recommendation: "Crop Recommendations",
    weather: "Weather Center",
    diseaseLog: "Health Logging",
    assistant: "Expert Advisory Assistant",
    officerDashboard: "Officer Portal",
    logout: "Log Out",
    login: "Log In",
    register: "Register Farmer",
    farmerId: "Farmer ID",
    role: "User Role",
    preferredLang: "Preferred Language",
    mobile: "Mobile Number",
    village: "Village",
    state: "State",
    district: "District",
    name: "Full Name",
    password: "Password",
    activeCrop: "Active Crop",
    riskScore: "Crop Risk Score",
    soilStatus: "Soil Status",
    weatherStatus: "Weather Status",
    drySpellRisk: "Dry Spell Risk",
    expertCases: "Expert cases",
    soilType: "Soil Type",
    soilPh: "Soil pH",
    landSize: "Land Size (Acres)",
    irrigation: "Irrigation Method",
    groundwater: "Groundwater Depth (m)",
    history: "Crop History",
    save: "Save Profile",
    loading: "Loading platform...",
    alerts: "Recent Alerts",
    noAlerts: "No active alerts. System running safely.",
    confidence: "Confidence",
    reasons: "Why this recommendation?",
    yield: "Yield Potential",
    risks: "Potential Risks",
    diagnoseTitle: "AI Disease Diagnosis",
    symptoms: "Symptoms Detected",
    treatment: "Treatment recommendation",
    voiceRecording: "Voice Advisory",
    chatPrompt: "Ask assistant something...",
    send: "Send",
    officerRemarks: "Officer Remarks",
    assignedOfficer: "Assigned Officer",
    status: "Status",
    greeting: "Namaste",
    villageLabel: "Village",
    farmRiskScore: "Farm Risk Score",
    suitabilityIndex: "Suitability Index",
    weatherRisk: "Weather Risk",
    waterRisk: "Water Risk",
    diseaseRisk: "Disease Risk",
    dashboardMetrics: "Agricultural Dashboard Metrics",
    soilLabel: "Soil",
    weatherForecast: "Weather Forecast",
    details: "Details",
    tempLabel: "Temp",
    humidityLabel: "Humidity",
    rainProb: "Rain Prob.",
    windLabel: "Wind",
    recentDiagnosis: "Recent Diagnosis Tickets",
    newUpload: "New Upload",
    noReports: "No recent crop disease reports filed.",
    configureFarm: "Configure Farm Profile",
    chatWithAssistant: "Chat with Assistant",
    alertCenter: "Alert Center",
    recommendedAction: "Recommended Action",
    tryAgain: "Try Again"
  },
  hi: {
    title: "KisanVriddhi",
    tagline: "किसानों को बुद्धिमत्ता से सशक्त बनाना",
    dashboard: "डैशबोर्ड",
    farmProfile: "कृषि प्रोफ़ाइल",
    recommendation: "फसल सिफारिशें",
    weather: "मौसम केंद्र",
    diseaseLog: "स्वास्थ्य लॉगिंग",
    assistant: "किसान सलाहकार सहायक",
    officerDashboard: "अधिकारी पोर्टल",
    logout: "लॉग आउट",
    login: "लॉग इन",
    register: "किसान पंजीकरण",
    farmerId: "किसान आईडी",
    role: "उपयोगकर्ता भूमिका",
    preferredLang: "पसंदीदा भाषा",
    mobile: "मोबाइल नंबर",
    village: "गाँव",
    state: "राज्य",
    district: "जिला",
    name: "पूरा नाम",
    password: "पासवर्ड",
    activeCrop: "सक्रिय फसल",
    riskScore: "फसल जोखिम स्कोर",
    soilStatus: "मिट्टी की स्थिति",
    weatherStatus: "मौसम की स्थिति",
    drySpellRisk: "सूखा जोखिम",
    expertCases: "विशेषज्ञ मामले",
    soilType: "मिट्टी का प्रकार",
    soilPh: "मिट्टी का पीएच (pH)",
    landSize: "भूमि का आकार (एकड़)",
    irrigation: "सिंचाई विधि",
    groundwater: "भूजल स्तर गहराई (मीटर)",
    history: "फसल इतिहास",
    save: "प्रोफ़ाइल सहेजें",
    loading: "लोड हो रहा है...",
    alerts: "हालिया अलर्ट",
    noAlerts: "कोई सक्रिय अलर्ट नहीं। सुरक्षित संचालन।",
    confidence: "विश्वास दर",
    reasons: "इस फसल की सिफारिश क्यों?",
    yield: "संभावित उपज",
    risks: "संभावित जोखिम",
    diagnoseTitle: "एआई रोग निदान",
    symptoms: "पाए गए लक्षण",
    treatment: "उपचार की सिफारिश",
    voiceRecording: "आवाज इनपुट",
    chatPrompt: "सहायक से कुछ पूछें...",
    send: "भेजें",
    officerRemarks: "अधिकारी की टिप्पणी",
    assignedOfficer: "नियुक्त अधिकारी",
    status: "स्थिति",
    greeting: "नमस्ते",
    villageLabel: "गाँव",
    farmRiskScore: "कृषि जोखिम स्कोर",
    suitabilityIndex: "उपयुक्तता सूचकांक",
    weatherRisk: "मौसम जोखिम",
    waterRisk: "जल जोखिम",
    diseaseRisk: "रोग जोखिम",
    dashboardMetrics: "कृषि डैशबोर्ड मेट्रिक्स",
    soilLabel: "मिट्टी",
    weatherForecast: "मौसम पूर्वानुमान",
    details: "विवरण",
    tempLabel: "तापमान",
    humidityLabel: "आर्द्रता",
    rainProb: "वर्षा संभावना",
    windLabel: "हवा",
    recentDiagnosis: "हालिया रोग निदान टिकट",
    newUpload: "नई अपलोड",
    noReports: "कोई हालिया फसल रोग रिपोर्ट दर्ज नहीं।",
    configureFarm: "कृषि प्रोफ़ाइल कॉन्फ़िगर करें",
    chatWithAssistant: "सहायक से बात करें",
    alertCenter: "अलर्ट केंद्र",
    recommendedAction: "अनुशंसित कार्रवाई",
    tryAgain: "पुनः प्रयास करें"
  },
  ml: {
    title: "KisanVriddhi",
    tagline: "കർഷകരെ ബുദ്ധിവൈഭവത്തിലൂടെ ശക്തിപ്പെടുത്തുന്നു",
    dashboard: "ഡാഷ്‌ബോർഡ്",
    farmProfile: "ഫാം പ്രൊഫൈൽ",
    recommendation: "വിള നിർദ്ദേശങ്ങൾ",
    weather: "കാലാവസ്ഥാ കേന്ദ്രം",
    diseaseLog: "ആരോഗ്യ വിവരങ്ങൾ",
    assistant: "വിദഗ്ദ്ധോപദേശ സഹായി",
    officerDashboard: "ഓഫീസർ പോർട്ടൽ",
    logout: "ലോഗ് ഔട്ട്",
    login: "ലോഗ് ഇൻ",
    register: "കർഷക രജിസ്ട്രേഷൻ",
    farmerId: "കർഷക ഐഡി",
    role: "ഉപയോക്തൃ റോൾ",
    preferredLang: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    mobile: "മൊബൈൽ നമ്പർ",
    village: "ഗ്രാമം",
    state: "സംസ്ഥാനം",
    district: "ജില്ല",
    name: "പൂർണ്ണമായ പേര്",
    password: "പാസ്‌വേഡ്",
    activeCrop: "നിലവിലെ വിള",
    riskScore: "വിള അപായ സാധ്യത",
    soilStatus: "മണ്ണിന്റെ അവസ്ഥ",
    weatherStatus: "കാലാവസ്ഥാ അവസ്ഥ",
    drySpellRisk: "വരൾച്ച സാധ്യത",
    expertCases: "വിദഗ്ദ്ധ കേസുകൾ",
    soilType: "മണ്ണിന്റെ തരം",
    soilPh: "മണ്ണിന്റെ pH",
    landSize: "സ്ഥലത്തിന്റെ അളവ് (ഏക്കർ)",
    irrigation: "നനയ്ക്കുന്ന രീതി",
    groundwater: "ഭൂഗർഭജല താഴ്ച (മീറ്റർ)",
    history: "കൃഷി ചരിത്രം",
    save: "പ്രൊഫൈൽ സേവ് ചെയ്യുക",
    loading: "ലോഡിംഗ്...",
    alerts: "അടുത്തകാലത്തെ അലേർട്ടുകൾ",
    noAlerts: "അലേർട്ടുകൾ ഒന്നും ലഭ്യമല്ല. സുരക്ഷിതം.",
    confidence: "വിശ്വാസ്യത ശതമാനം",
    reasons: "എന്തുകൊണ്ട് ഈ ശുപാർശ?",
    yield: "സാധ്യമായ വിളവ്",
    risks: "സാധ്യമായ ദോഷങ്ങൾ",
    diagnoseTitle: "AI രോഗനിർണ്ണയം",
    symptoms: "കണ്ടെത്തിയ ലക്ഷണങ്ങൾ",
    treatment: "ചികിത്സാ ശുപാർശകൾ",
    voiceRecording: "വോയ്‌സ് റെക്കോർഡിംഗ്",
    chatPrompt: "ചോദ്യങ്ങൾ ചോദിക്കുക...",
    send: "അയക്കുക",
    officerRemarks: "ഓഫീസറുടെ കുറിപ്പ്",
    assignedOfficer: "ചുമതലയുള്ള ഓഫീസർ",
    status: "നിലവിലെ അവസ്ഥ",
    greeting: "നമസ്കാരം",
    villageLabel: "ഗ്രാമം",
    farmRiskScore: "കൃഷി അപകട സ്കോർ",
    suitabilityIndex: "അനുയോജ്യതാ സൂചിക",
    weatherRisk: "കാലാവസ്ഥ അപകടം",
    waterRisk: "ജല അപകടം",
    diseaseRisk: "രോഗ അപകടം",
    dashboardMetrics: "കൃഷി ഡാഷ്‌ബോർഡ് മെട്രിക്കുകൾ",
    soilLabel: "മണ്ണ്",
    weatherForecast: "കാലാവസ്ഥ പ്രവചനം",
    details: "വിശദാംശങ്ങൾ",
    tempLabel: "താപനില",
    humidityLabel: "ഈർപ്പം",
    rainProb: "മഴ സാധ്യത",
    windLabel: "കാറ്റ്",
    recentDiagnosis: "സമീപകാല രോഗ നിർണ്ണയ ടിക്കറ്റുകൾ",
    newUpload: "പുതിയ അപ്ലോഡ്",
    noReports: "സമീപകാലത്ത് ഒരു രോഗ റിപ്പോർട്ടും ഫയൽ ചെയ്തിട്ടില്ല.",
    configureFarm: "ഫാം പ്രൊഫൈൽ ക്രമീകരിക്കുക",
    chatWithAssistant: "സഹായിയോട് സംസാരിക്കുക",
    alertCenter: "അലേർട്ട് കേന്ദ്രം",
    recommendedAction: "ശുപാർശ ചെയ്ത നടപടി",
    tryAgain: "വീണ്ടും ശ്രമിക്കുക"
  },
  te: {
    title: "KisanVriddhi",
    tagline: "రైతులను మేధస్సుతో శక్తివంతం చేయడం",
    dashboard: "డాష్‌బోర్డ్",
    farmProfile: "వ్యవసాయ ప్రొఫైల్",
    recommendation: "పంట సిఫార్సులు",
    weather: "వాతావరణ కేంద్రం",
    diseaseLog: "ఆరోగ్య లాగింగ్",
    assistant: "నిపుణుల సలహా సహాయకుడు",
    officerDashboard: "అధికారి పోర్టల్",
    logout: "లాగ్ అవుట్",
    login: "లాగ్ ఇన్",
    register: "రైతు నమోదు",
    farmerId: "రైతు ఐడి",
    role: "వినియోగదారు పాత్ర",
    preferredLang: "ప్రాధాన్యత భాష",
    mobile: "మొబైల్ సంఖ్య",
    village: "గ్రామం",
    state: "రాష్ట్రం",
    district: "జిల్లా",
    name: "పూర్తి పేరు",
    password: "పాస్‌వర్డ్",
    activeCrop: "ప్రస్తుత పంట",
    riskScore: "పంట ప్రమాద స్కోరు",
    soilStatus: "నేల స్థితి",
    weatherStatus: "వాతావరణ స్థితి",
    drySpellRisk: "కరువు ప్రమాదం",
    expertCases: "నిపుణుల కేసులు",
    soilType: "నేల రకం",
    soilPh: "నేల pH",
    landSize: "భూమి పరిమాణం (ఎకరాలు)",
    irrigation: "నీటిపారుదల పద్ధతి",
    groundwater: "భూగర్భ జలాల లోతు (మీ)",
    history: "పంటల చరిత్ర",
    save: "ప్రొఫైల్ సేవ్ చేయి",
    loading: "లోడ్ అవుతోంది...",
    alerts: "ఇటీవలి హెచ్చరికలు",
    noAlerts: "ఎలాంటి హెచ్చరికలు లేవు. సురक्षितంగా నడుస్తోంది.",
    confidence: "విశ్వాస శాతం",
    reasons: "ఈ పంట ఎందుకు సిఫార్సు చేయబడింది?",
    yield: "దిగుబడి సంభావ్యత",
    risks: "సంభావ్య ప్రమాదాలు",
    diagnoseTitle: "AI వ్యాధి నిర్ధారణ",
    symptoms: "గుర్తించిన లక్షణాలు",
    treatment: "చికిత్స సిఫార్సు",
    voiceRecording: "వాయిస్ రికార్డింగ్",
    chatPrompt: "అసిస్టెంట్‌ను అడగండి...",
    send: "పంపించు",
    officerRemarks: "అధికారి వ్యాఖ్యలు",
    assignedOfficer: "అప్పగించిన అధికారి",
    status: "స్థితి",
    greeting: "నమస్కారం",
    villageLabel: "గ్రామం",
    farmRiskScore: "వ్యవసాయ ప్రమాద స్కోరు",
    suitabilityIndex: "అనుకూలత సూచిక",
    weatherRisk: "వాతావరణ ప్రమాదం",
    waterRisk: "నీటి ప్రమాదం",
    diseaseRisk: "వ్యాధి ప్రమాదం",
    dashboardMetrics: "వ్యవసాయ డాష్‌బోర్డ్ మెట్రిక్స్",
    soilLabel: "నేల",
    weatherForecast: "వాతావరణ సూచన",
    details: "వివరాలు",
    tempLabel: "ఉష్ణోగ్రత",
    humidityLabel: "తేమ",
    rainProb: "వర్షం సంభావ్యత",
    windLabel: "గాలి",
    recentDiagnosis: "ఇటీవలి వ్యాధి నిర్ధారణ టిక్కెట్లు",
    newUpload: "కొత్త అప్‌లోడ్",
    noReports: "ఇటీవల ఎలాంటి పంట వ్యాధి నివేదికలు నమోదు కాలేదు.",
    configureFarm: "వ్యవసాయ ప్రొఫైల్ కాన్ఫిగర్ చేయండి",
    chatWithAssistant: "సహాయకుడితో మాట్లాడండి",
    alertCenter: "హెచ్చరిక కేంద్రం",
    recommendedAction: "సిఫార్సు చేయబడిన చర్య",
    tryAgain: "మళ్ళీ ప్రయత్నించండి"
  }
};

export function getTranslation(key: string, lang: string = "en"): string {
  const dict = TRANSLATE_DICT[lang] || TRANSLATE_DICT["en"];
  return dict[key] || TRANSLATE_DICT["en"][key] || key;
}
